name: 📰 Send Newsletter

on:
  # 03:30 UTC = 09:00 IST; repeat on day 1,6,11,16,21,26,31 → “every ~5 days”
  schedule:
    - cron: '30 3 1,6,11,16,21,26,31 * *'
  workflow_dispatch:

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run newsletter pipeline
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        YOUTUBE_API_KEY:    ${{ secrets.YOUTUBE_API_KEY }}
        SMTP_HOST: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
      run: |
        ./run_pipeline.sh
