name: 📰 Weekly Newsletter

on:
  schedule:
    # 03:30 UTC = 09:00 IST every Monday
    - cron: '30 3 * * 1'
  workflow_dispatch:        # (optional) manual trigger

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full pipeline
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          YOUTUBE_API_KEY:    ${{ secrets.YOUTUBE_API_KEY }}
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          # 1. Embed + rank + summarise articles
          python -m src.articles.embed_articles
          python -m src.articles.rank
          python -m src.articles.summarise

          # 2. Embed + rank + summarise YouTube
          python -m src.youtube.embed_videos
          python -m src.youtube.youtube_rank
          python -m src.youtube.youtube_summarise

          # 3. Render & send
          python -m src.render_newsletter
          python -m src.smtp_mailer

          # 4. House-keeping
          python -m src.housekeeping
